package in.hibernate;
// Generated Apr 1, 2013 8:20:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserEvent generated by hbm2java
 */
public class UserEvent  implements java.io.Serializable {


     private Integer eventid;
     private Reg reg;
     private Date eventdate;
     private String eventdesc;

    public UserEvent() {
    }

    public UserEvent(Reg reg, Date eventdate, String eventdesc) {
       this.reg = reg;
       this.eventdate = eventdate;
       this.eventdesc = eventdesc;
    }
   
    public Integer getEventid() {
        return this.eventid;
    }
    
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }
    public Reg getReg() {
        return this.reg;
    }
    
    public void setReg(Reg reg) {
        this.reg = reg;
    }
    public Date getEventdate() {
        return this.eventdate;
    }
    
    public void setEventdate(Date eventdate) {
        this.eventdate = eventdate;
    }
    public String getEventdesc() {
        return this.eventdesc;
    }
    
    public void setEventdesc(String eventdesc) {
        this.eventdesc = eventdesc;
    }




}


